# -*- coding: utf-8 -*-
"""Traducciones EN de los 3 artículos + mapa de estructura (h2 / li / p)."""

STRUCT = {
 "llantera":  dict(h2={3,9,19,23},     li={4,5,6,7,8,11,12,13,14,15,16,17,18,20,21,22}, drop={25}),
 "complejo":  dict(h2={3,10,16,22,24}, li={6,7,8,12,13,14,19,20,21},                    drop={27}),
 "logistico": dict(h2={3,11,19,26,29}, li={6,7,8,9,14,15,16,17,22,23,24,25},            drop={32}),
}

EN = {
"llantera": [
"Special Industrial Project: Underground Engineering for a Tire Plant",
"At Caabsa Steel México we are proud to share the details of challenging projects: the construction of a five-level industrial building in Cuernavaca, Morelos, designed specifically for a leading tire manufacturer.",
"This project stands out for its technical complexity and for integrating tailor-made solutions that guarantee the efficient, safe operation of specialized machinery.",
"Project overview",
"Location: Cuernavaca, State of Morelos.",
"Client: A major company in the automotive sector (tire manufacturing).",
"Type of construction: A five-level industrial building — three basement levels and two above ground.",
"Total built area: more than 2,000 m²",
"Main objective: To house and protect special equipment for the plant's production processes, and to optimize material flow through high-performance industrial installations.",
"Technical and special features",
"The nature of the tire manufacturing process called for very specific engineering solutions:",
"Robust structure and deep foundations: Because the building has three underground levels, exhaustive geotechnical studies were carried out to design a foundation capable of supporting not only the weight of the structure, but also the dynamic loads and vibrations of heavy machinery.",
"Making the most of the subsoil: The three basement levels were designed to house equipment that requires controlled temperature, acoustic insulation and security. This frees up space at grade and optimizes the plant's internal logistics.",
"Specialized extraction and ventilation: High-capacity extractors were installed to guarantee air quality and the removal of particles and gases from the vulcanizing process and material handling. These systems comply with environmental and industrial safety regulations.",
"Overhead traveling crane: One of the most notable installations is the overhead traveling crane on one of the upper levels. This equipment is essential for moving molds, raw materials and heavy finished products, optimizing production times and reducing risk for operators.",
"Protection of special equipment: Advanced protective measures were implemented, including:",
"Fire detection and suppression systems.",
"Humidity and temperature control in critical areas.",
"Special insulation and coatings to protect machinery from corrosive agents.",
"Challenges and solutions during execution",
"Geotechnical challenge: Building three basement levels on the Cuernavaca site required a diaphragm wall system and careful groundwater management to guarantee stability during excavation.",
"Integrating the overhead crane: Installing this equipment demanded specific structural reinforcement in the roof slab and millimetric coordination with the electrical and safety systems.",
"Coordination of installations: The coexistence of extraction systems, high-power electrical service and the overhead crane required a BIM (Building Information Modeling) model to avoid clashes and optimize space.",
"Conclusion",
"This project in Cuernavaca is a clear example of how tailor-made engineering can solve the most demanding needs of industry. The combination of underground spaces, specialized installations and large equipment such as the overhead traveling crane allowed us to deliver a functional, safe building, ready for the challenges of modern tire production.",
"",
],
"complejo": [
"Industrial Complex: Designed for Productivity and Wellbeing",
"At Grupo Caabsa Steel México we believe a workplace should be not only functional, but inspiring. That is why, in our turnkey project, we developed an office center that combines modernity, comfort and efficiency, as part of an industrial complex of more than 25,000 square meters.",
"This integral project includes not only a first-class administrative building, but also production areas, warehouses, silo installations, truck scales, internal roadways and service areas — all designed to optimize our client's operations and drive their growth.",
"Offices that inspire: a space designed around people",
"The new office center is much more than a place to work. It is an environment designed to encourage collaboration, focus and the wellbeing of the administrative team.",
"What you will find in this building:",
"Spacious, bright administrative areas: Designed with open-office concepts that favor communication and flexibility.",
"Meeting and conference rooms: Spaces equipped with state-of-the-art technology for executive meetings, presentations and video conferencing.",
"Break and service areas: Areas designed for staff comfort, promoting a balance between productivity and wellbeing.",
"Every corner has been carefully planned to offer a superior work experience, with quality finishes, natural light and an intelligent layout.",
"Industrial warehouse: efficiency and capacity at scale",
"The operational heart of the complex features a large industrial warehouse and state-of-the-art production areas. These spaces were designed to:",
"Maximize storage capacity.",
"Guarantee safety at all times.",
"Facilitate internal logistics and material flow.",
"The integration of technology and functional design means every square meter works in favor of productivity.",
"Technology and heavy infrastructure: high-performance silos and truck scales",
"One of the great challenges of this project was incorporating specialized installations for four industrial silos and a truck weighing system. These structures not only increase production and storage capacity, they also optimize loading, unloading and raw material control.",
"Key benefits:",
"Precision in weighing and inventory control.",
"Faster receipt and dispatch of materials.",
"Reduced downtime in the operation.",
"Internal mobility: strategic roadways and service areas",
"To guarantee a smooth, safe operation, the complex features perfectly laid out internal roadways that allow efficient transit of heavy and light vehicles. Service areas have also been strategically placed to facilitate daily maintenance and logistics.",
"An integral project, a total solution",
"This development is a clear example of how a turnkey solution can completely transform a company's operating capacity. From the foundation to the final architectural details, every element was executed to the highest quality standards.",
"At Caabsa Steel México, we build spaces that drive businesses forward.",
"",
],
"logistico": [
"High-Performance Logistics Centers: Planning, Precision and Certified Quality",
"In today's economy, supply chain efficiency is the factor that determines a company's competitiveness. In this context, logistics centers have become strategic infrastructure for industrial and commercial growth. Modern facilities are designed not just to store, but to maximize operations, optimize response times and guarantee safety in every process.",
"For a specialized construction company, developing this type of infrastructure goes far beyond erecting an industrial building. It requires integral planning, precise execution and rigorous compliance with the highest quality standards.",
"Planning: the starting point of operational success",
"Before the first stone is laid, meticulous planning marks the difference between a smooth operation and a center full of logistical limitations. Good design anticipates the future.",
"Key aspects in this initial phase:",
"Strategic location: Analysis of proximity to main roads, quick access and transport hubs that facilitate distribution.",
"Logistics flow: Intelligent design of entrances, exits and internal circulation to avoid bottlenecks and maximize productivity.",
"Operating capacity: Precise sizing of loading docks, maneuvering yards and storage zones, adapted to the client's real needs.",
"Scalability: Future projection, allowing for expansions without interfering with daily operations.",
"Well-considered planning ensures the logistics center runs like clockwork from its first day of operation.",
"Precise execution: where engineering comes to life",
"The execution phase is when the vision becomes reality. Here, coordination between disciplines, the selection of high-quality materials and meeting deadlines are absolutely critical.",
"In building first-class logistics centers, we stand out for our ability to develop:",
"Large-scale structures: Designed with high strength to withstand the demands of the operation.",
"Specialized loading docks: Configured for intensive, high-rotation operations.",
"High-performance industrial floors: Flat, durable surfaces designed to withstand continuous heavy traffic from forklifts and machinery.",
"Drainage systems and internal networks: Efficient infrastructure that guarantees operational continuity in any conditions.",
"Every construction detail has a direct impact on the client's productivity and profitability.",
"The mark of quality: ISO 9001:2015 certification",
"Holding ISO 9001:2015 certification is not just a plaque on the wall; it is a tangible commitment to excellence and continuous improvement. For our clients, it translates into peace of mind and confidence.",
"This certification guarantees:",
"Standardized, controlled processes: Every project follows clear guidelines that minimize uncertainty.",
"Continuous improvement: We learn from every project to do the next one better.",
"Customer focus: Every decision is made with the aim of exceeding the end user's expectations.",
"Fewer errors: A systematic way of working reduces rework and optimizes resources.",
"More than building: we create strategic infrastructure",
"A well-conceived logistics center is not a simple container for products; it is a platform that drives operations, reduces costs and dramatically improves a company's competitiveness in a global market.",
"That is why choosing the construction company is a crucial business decision. You need a partner with experience, strategic vision and, above all, quality certifications that back up their work.",
"Conclusion",
"Building logistics centers is a discipline that demands surgical precision, deep technical knowledge and an absolute commitment to quality. From the first line drawn in planning to the handover of keys, every stage must be executed to the most rigorous standards.",
"A construction company certified to ISO 9001:2015 does not only build spaces of concrete and steel; it delivers reliable, efficient solutions ready for the logistics challenges of the future.",
"",
],
}

META = {
 "llantera": dict(slug={"es":"ingenieria-subterranea-planta-llantas","en":"underground-engineering-tire-plant"},
   photo="images/proyectos/bridgestone-mixing/01.jpg", chip="chip--ind",
   gallery=["bridgestone-mixing/02.jpg","bridgestone-mixing/03.jpg","bridgestone-mixing/04.jpg"],
   cat={"es":"Industrial","en":"Industrial"},
   meta_lbl={"es":"Bridgestone · Cuernavaca, Morelos","en":"Bridgestone · Cuernavaca, Morelos"},
   desc={"es":"Cómo construimos un edificio industrial de 5 niveles con 3 sótanos, muros milán y grúa viajera para la planta de Bridgestone en Cuernavaca, Morelos.",
         "en":"How we built a five-level industrial building with three basement levels, diaphragm walls and an overhead traveling crane for Bridgestone's plant in Cuernavaca, Morelos."}),
 "complejo": dict(slug={"es":"complejo-industrial-llave-en-mano-25000-m2","en":"turnkey-industrial-complex-25000-m2"},
   photo="images/proyectos/tintas-sanchez/01.jpg", chip="chip--corp",
   gallery=["tintas-sanchez/02.jpg","tintas-sanchez/03.jpg","tintas-sanchez/04.jpg"],
   cat={"es":"Corporativo","en":"Corporate"},
   meta_lbl={"es":"Grupo Sánchez · Hidalgo · 25,000 m²","en":"Grupo Sánchez · Hidalgo · 25,000 m²"},
   desc={"es":"Oficinas, almacén, producción, silos y básculas en un complejo industrial de más de 25,000 m² entregado llave en mano en Tepeji del Río, Hidalgo.",
         "en":"Offices, warehousing, production, silos and truck scales in an industrial complex of more than 25,000 m² delivered turnkey in Tepeji del Río, Hidalgo."}),
 "logistico": dict(slug={"es":"centros-logisticos-alto-rendimiento","en":"high-performance-logistics-centers"},
   photo="images/proyectos/andenes/01.jpg", chip="chip--log",
   gallery=["andenes/02.jpg","andenes/03.jpg","andenes/04.jpg"],
   cat={"es":"Logístico","en":"Logistics"},
   meta_lbl={"es":"Calidad certificada ISO 9001:2015","en":"ISO 9001:2015 certified quality"},
   desc={"es":"Planeación, ejecución de precisión y calidad certificada ISO 9001:2015 en la construcción de centros de distribución de alto rendimiento.",
         "en":"Planning, precise execution and ISO 9001:2015 certified quality in the construction of high-performance distribution centers."}),
}
ORDER = ["llantera", "complejo", "logistico"]
