# -*- coding: utf-8 -*-
"""Catálogo de proyectos con los datos reales del cliente
(Presentación Proyectos Web.pptx + Contenido Blog.docx + docs de carpeta)."""

# estados nuevos que aparecen en la presentación
EXTRA_STATES = {
 "michoacan":     dict(name={"es":"Michoacán","en":"Michoacán"}, region="occidente",
    cities={"es":"Morelia","en":"Morelia"}),
 "aguascalientes":dict(name={"es":"Aguascalientes","en":"Aguascalientes"}, region="bajio",
    cities={"es":"el corredor industrial de Aguascalientes","en":"the Aguascalientes industrial corridor"}),
 "veracruz":      dict(name={"es":"Veracruz","en":"Veracruz"}, region="south",
    cities={"es":"Orizaba y su valle industrial","en":"Orizaba and its industrial valley"}),
}

def _p(slug, client, state, sector, photos, kind_es, kind_en, m2=None,
       scope_es=None, scope_en=None, about_es=None, about_en=None, city=None, article=None):
    return dict(slug=slug, client=client, state=state, sector=sector, photos=photos,
                kind={"es":kind_es,"en":kind_en}, m2=m2,
                scope={"es":scope_es or [], "en":scope_en or []},
                about={"es":about_es or "", "en":about_en or ""},
                city={"es":city,"en":city} if city else {}, article=article)

E = ["Estructura metálica","Obra civil"]
EE = ["Structural steel","Civil works"]

PROJECTS = [
# ─────────── ESTADO DE MÉXICO ───────────
_p("bosch","Bosch","estado-de-mexico","automotive",1,
   "Nave industrial","Industrial facility","21,000 m²",
   ["Nave industrial de gran superficie"]+E, ["Large-footprint industrial facility"]+EE,
   "Nave industrial de 21,000 m² para Bosch, proveedor Tier 1 de la industria automotriz, en el Parque Industrial Exportec, Estado de México.",
   "A 21,000 m² industrial facility for Bosch, a Tier 1 automotive supplier, in the Exportec Industrial Park, State of Mexico.",
   city="Parque Industrial Exportec"),
_p("bardahl","Bardahl","estado-de-mexico","industrial",1,
   "Nave industrial","Industrial facility","19,888 m²",
   ["Nave industrial"]+E, ["Industrial facility"]+EE,
   "Nave industrial de 19,888 m² para Bardahl, fabricante de lubricantes, en el Parque Industrial Toluca 2000.",
   "A 19,888 m² industrial facility for Bardahl, a lubricants manufacturer, in the Toluca 2000 Industrial Park.",
   city="Parque Industrial Toluca 2000"),
_p("lear","Lear Corporation","estado-de-mexico","automotive",1,
   "Nave industrial","Industrial facility","11,493 m²",
   ["Nave industrial"]+E, ["Industrial facility"]+EE,
   "Nave industrial de 11,493 m² para Lear Corporation, proveedor global de asientos y sistemas eléctricos para la industria automotriz.",
   "An 11,493 m² industrial facility for Lear Corporation, a global supplier of seating and electrical systems to the automotive industry.",
   city="Parque Industrial Toluca 2000"),
_p("la-moderna","La Moderna","estado-de-mexico","logistics",2,
   "Centro de distribución","Distribution center","18,500 m²",
   ["Estructura de gran escala para las exigencias de la operación",
    "Andenes de carga especializados para alta rotación",
    "Pisos industriales de alto desempeño para tráfico pesado continuo",
    "Sistemas de drenaje y redes internas",
    "Patio de maniobras y circulación optimizada",
    "Dimensionamiento previsto para futuras ampliaciones"],
   ["Large-scale structure built for the demands of the operation",
    "Specialized loading docks for high-rotation operations",
    "High-performance industrial floors for continuous heavy traffic",
    "Drainage systems and internal networks",
    "Maneuvering yard and optimized circulation",
    "Sizing planned for future expansions"],
   "Centro de distribución de 18,500 m² sobre el corredor Toluca-Atlacomulco. Se planeó desde la ubicación estratégica y el flujo logístico hasta el dimensionamiento de andenes, patios y zonas de almacenaje, con escalabilidad prevista para ampliaciones futuras sin interferir con la operación diaria.",
   "An 18,500 m² distribution center on the Toluca-Atlacomulco corridor. It was planned from its strategic location and logistics flow through to the sizing of docks, yards and storage areas, with scalability built in for future expansions without disrupting daily operations.",
   city="Toluca-Atlacomulco", article="logistico"),
_p("finsa-bosch","FINSA · Robert Bosch","estado-de-mexico","automotive",4,
   "Nave industrial","Industrial facility","5,800 m²",
   ["Obra civil","Cimentación","Estructura metálica","Acabados","Laminación","Servicios auxiliares"],
   ["Civil works","Foundations","Structural steel","Finishes","Roofing and cladding","Auxiliary services"],
   "Nave industrial Robert Bosch de 5,800 m² en San Martín Obispo, ejecutada de la cimentación a los servicios auxiliares.",
   "A 5,800 m² Robert Bosch industrial facility in San Martín Obispo, delivered from foundations through auxiliary services.",
   city="San Martín Obispo"),
_p("interjet","Interjet","estado-de-mexico","aerospace",2,
   "Hangar","Hangar","8,500 m²",
   ["Hangar de gran claro","Estructura metálica"], ["Long-span hangar","Structural steel"],
   "Hangar de 8,500 m² en el Aeropuerto Internacional de Toluca, con estructura de gran claro libre para operación y mantenimiento de aeronaves.",
   "An 8,500 m² hangar at Toluca International Airport, with a long-span column-free structure for aircraft operation and maintenance.",
   city="Aeropuerto de Toluca"),
_p("soriana","Soriana","estado-de-mexico","industrial",1,
   "Estructura metálica","Structural steel","8,500 m²",
   ["Estructura metálica","Montaje en obra"], ["Structural steel","On-site erection"],
   "Estructura metálica de 8,500 m² en Cuautitlán Izcalli para Soriana.",
   "8,500 m² of structural steel in Cuautitlán Izcalli for Soriana.",
   city="Cuautitlán Izcalli"),
_p("cimsa","Grupo CIMSA · Coca-Cola","estado-de-mexico","food",1,
   "Pisos industriales","Industrial flooring","36,000 m²",
   ["Pisos industriales de alto desempeño"], ["High-performance industrial flooring"],
   "36,000 m² de pisos industriales para Grupo CIMSA (Coca-Cola), en el Parque Industrial El Coecillo.",
   "36,000 m² of industrial flooring for Grupo CIMSA (Coca-Cola), in the El Coecillo Industrial Park.",
   city="Parque Industrial El Coecillo"),
_p("quimica-apollo","Química Apollo","estado-de-mexico","industrial",2,
   "Nave industrial y oficinas","Industrial facility and offices","4,300 m²",
   ["Nave industrial","Oficinas"]+E, ["Industrial facility","Offices"]+EE,
   "Nave industrial y oficinas de 4,300 m² para Química Apollo, en el Parque Industrial Exportec II.",
   "A 4,300 m² industrial facility and offices for Química Apollo, in the Exportec II Industrial Park.",
   city="Parque Industrial Exportec II"),
_p("dalton-honda","Dalton Honda","estado-de-mexico","automotive",1,
   "Agencia automotriz","Automotive dealership","5,600 m²",
   ["Distribuidor automotriz","Obra civil","Acabados"], ["Automotive dealership","Civil works","Finishes"],
   "Agencia Honda Tollocan de 5,600 m² en Metepec, desarrollada y ejecutada para Dalton Evolución.",
   "The 5,600 m² Honda Tollocan dealership in Metepec, developed and delivered for Dalton Evolución.",
   city="Metepec"),
_p("aventis-pharma","Aventis Pharma","estado-de-mexico","pharma",2,
   "Planta farmacéutica","Pharmaceutical plant",None,
   ["Nave industrial para proceso farmacéutico","Acabados de grado farmacéutico","Estructura metálica","Obra civil"],
   ["Industrial facility for pharmaceutical processing","Pharmaceutical-grade finishes","Structural steel","Civil works"],
   "Planta para Aventis Pharma en el Estado de México, construida bajo los requisitos de control y acabados que exige la industria farmacéutica.",
   "Plant for Aventis Pharma in the State of Mexico, built to the control and finish requirements demanded by the pharmaceutical industry."),
_p("gates","Gates","estado-de-mexico","automotive",6,
   "Incremento de altura en nave en producción","Height increase of an operating facility","1,500 m²",
   ["Obra civil","Laminación","Instalaciones especiales","Incremento de altura estructural"],
   ["Civil works","Roofing and cladding","Special installations","Structural height increase"],
   "Ampliación de nave industrial del proyecto High Speed en la planta de Gates Toluca, fabricante de bandas de transmisión. La obra se ejecutó con la planta en operación y durante el apogeo del COVID-19, resolviendo con soluciones técnicas los retos que fueron surgiendo.",
   "Industrial facility expansion for the High Speed project at the Gates Toluca plant, a manufacturer of power transmission belts. The work was carried out with the plant running and at the height of COVID-19, solving the challenges that arose with tailored technical solutions.",
   city="Toluca"),
_p("polynt","Polynt","estado-de-mexico","industrial",2,
   "Modificación de altura en edificio industrial","Height modification of an industrial building","1,500 m²",
   ["Vialidades","Base para tanques","Obra civil","Modificación de altura"],
   ["Internal roadways","Tank foundations","Civil works","Height modification"],
   "Adecuación de un edificio industrial existente, incluyendo bases para tanques y vialidades internas.",
   "Adaptation of an existing industrial building, including tank foundations and internal roadways."),
_p("tecnosol","Tecnosol","estado-de-mexico","industrial",2,
   "Ampliación de almacén en planta en producción","Warehouse expansion at an operating plant","3,000 m²",
   ["Proyecto completo","Ampliación de almacén","Laminación"],
   ["Full turnkey project","Warehouse expansion","Roofing and cladding"],
   "Tecnosol fabrica aerosoles para distintos sectores. La ampliación de almacén se realizó con la planta en operación.",
   "Tecnosol manufactures aerosols for various sectors. The warehouse expansion was carried out with the plant in operation."),

# ─────────── QUERÉTARO ───────────
_p("vesta","Vesta","queretaro","logistics",1,
   "Centro de distribución","Distribution center","21,000 m²",
   ["Obra civil","Cimentación","Estructura metálica","Acabados","Laminación","Servicios auxiliares"],
   ["Civil works","Foundations","Structural steel","Finishes","Roofing and cladding","Auxiliary services"],
   "Centro de distribución de 21,000 m² para Vesta en el Parque Industrial Bernardo Quintana, ejecutado de la obra civil a los servicios auxiliares.",
   "A 21,000 m² distribution center for Vesta in the Bernardo Quintana Industrial Park, delivered from civil works through auxiliary services.",
   city="Parque Industrial Bernardo Quintana"),
_p("ferrostaal","Ferrostaal","queretaro","industrial",1,
   "Nave industrial","Industrial facility","9,400 m²",
   ["Nave industrial"]+E, ["Industrial facility"]+EE,
   "Nave industrial de 9,400 m² para Ferrostaal en el Parque Industrial Finsa, Querétaro.",
   "A 9,400 m² industrial facility for Ferrostaal in the Finsa Industrial Park, Querétaro.",
   city="Parque Industrial Finsa"),
_p("martinrea-honsel","Martinrea Honsel","queretaro","automotive",7,
   "Oficinas corporativas y almacén","Corporate offices and warehouse","5,000 m²",
   ["Oficinas corporativas","Almacén","Ampliaciones y mejoras de planta"]+E,
   ["Corporate offices","Warehouse","Plant expansions and improvements"]+EE,
   "Oficinas corporativas y almacén de 5,000 m² en el Parque Industrial Querétaro. La relación con Martinrea Honsel suma más de ocho años continuos de ampliaciones y trabajos de mejora en su planta.",
   "5,000 m² of corporate offices and warehousing in the Querétaro Industrial Park. The relationship with Martinrea Honsel spans more than eight continuous years of expansions and improvement works at their plant.",
   city="Parque Industrial Querétaro"),
_p("metrocolor","Metrocolor","queretaro","industrial",5,
   "Nave industrial","Industrial facility",None,
   ["Nave industrial"]+E, ["Industrial facility"]+EE,
   "Nave industrial para Metrocolor de México en el lote 59 del Parque Industrial Finsa El Marqués, Querétaro.",
   "Industrial facility for Metrocolor de México on lot 59 of the Finsa El Marqués Industrial Park, Querétaro.",
   city="Parque Industrial Finsa El Marqués"),
_p("daewoo","Daewoo","queretaro","industrial",1,
   "Nave industrial y oficinas","Industrial facility and offices","3,000 m²",
   ["Nave industrial","Oficinas"]+E, ["Industrial facility","Offices"]+EE,
   "Nave industrial y oficinas de 3,000 m² para Daewoo en el Parque Industrial Bernardo Quintana.",
   "A 3,000 m² industrial facility and offices for Daewoo in the Bernardo Quintana Industrial Park.",
   city="Parque Industrial Bernardo Quintana"),
_p("kimberly-clark","Kimberly-Clark","queretaro","industrial",1,
   "Nave industrial","Industrial facility","2,000 m²",
   ["Nave industrial"]+E, ["Industrial facility"]+EE,
   "Nave industrial de 2,000 m² para Kimberly-Clark en San Juan del Río, Querétaro.",
   "A 2,000 m² industrial facility for Kimberly-Clark in San Juan del Río, Querétaro.",
   city="San Juan del Río"),
_p("robin","Robin","queretaro","industrial",5,
   "Nave industrial de producción","Industrial production facility",None,
   ["Nave industrial"]+E, ["Industrial facility"]+EE,
   "Nave industrial de producción construida en el corredor industrial de Querétaro.",
   "Industrial production facility built in the Querétaro industrial corridor."),

# ─────────── MORELOS ───────────
_p("saint-gobain","Saint-Gobain Glass","morelos","industrial",2,
   "Planta industrial","Industrial plant","15,000 m²",
   ["Planta industrial"]+E, ["Industrial plant"]+EE,
   "Planta industrial de 15,000 m² para Saint-Gobain Glass en Cuautla, Morelos.",
   "A 15,000 m² industrial plant for Saint-Gobain Glass in Cuautla, Morelos.",
   city="Cuautla"),
_p("bridgestone","Bridgestone","morelos","corporate",1,
   "Oficinas · centro de negocios","Offices · business center","2,500 m²",
   ["Oficinas corporativas","Centro de negocios","Obra civil"],
   ["Corporate offices","Business center","Civil works"],
   "Centro de negocios de 2,500 m² para Bridgestone en Cuernavaca, Morelos.",
   "A 2,500 m² business center for Bridgestone in Cuernavaca, Morelos.",
   city="Cuernavaca"),
_p("espejos-inteligentes","Espejos Inteligentes","morelos","automotive",8,
   "Ampliación de nave industrial y almacén","Industrial facility and warehouse expansion","2,500 m²",
   ["Terracerías","Cimentación","Laminación","Estructura metálica"],
   ["Earthworks","Foundations","Roofing and cladding","Structural steel"],
   "Ampliación para una planta de espejos inteligentes del sector automotriz, ejecutada de la terracería al montaje.",
   "Expansion for a smart-mirror plant serving the automotive sector, executed from earthworks through erection.",
   city="Cuernavaca"),
_p("bridgestone-mixing","Bridgestone","morelos","industrial",5,
   "Edificio industrial para proceso de mezclado","Industrial building for the mixing process","+2,000 m²",
   ["Edificio de 5 niveles: 3 sótanos y 2 niveles superiores","Cimentación profunda y muros milán",
    "Grúa viajera (puente grúa)","Sistemas de extracción y ventilación especializada",
    "Protección de equipos: detección y extinción de incendios, control de humedad y temperatura",
    "Coordinación con modelo BIM"],
   ["Five-level building: three basements and two upper levels","Deep foundations and diaphragm walls",
    "Overhead traveling crane","Specialized extraction and ventilation systems",
    "Equipment protection: fire detection and suppression, humidity and temperature control",
    "Coordination through a BIM model"],
   "Edificio industrial de 5 niveles —3 de ellos sótanos— para el área de mezclado de la planta de Bridgestone en Cuernavaca. La obra exigió estudios geotécnicos, muros milán y una grúa viajera para el movimiento de moldes y materia prima.",
   "A five-level industrial building — three of them basements — for the mixing area of Bridgestone's plant in Cuernavaca. The project required geotechnical studies, diaphragm walls and an overhead traveling crane to move molds and raw materials.",
   city="Cuernavaca", article="llantera"),

# ─────────── HIDALGO ───────────
_p("tintas-sanchez","Grupo Sánchez","hidalgo","corporate",4,
   "Complejo industrial llave en mano","Turnkey industrial complex","25,000 m²",
   ["Diseño arquitectónico","Ingeniería estructural","Nave de procesos y productos terminados (20,000 m²)",
    "Nave de materia prima, serigrafía y tambos","Edificio administrativo y laboratorio",
    "Subestación, cisternas y cuartos de bombas","Silos y básculas","Patios de maniobras y vialidades internas"],
   ["Architectural design","Structural engineering","Process and finished-goods facility (20,000 m²)",
    "Raw material, screen-printing and drum buildings","Administrative building and laboratory",
    "Substation, cisterns and pump rooms","Silos and truck scales","Maneuvering yards and internal roadways"],
   "Proyecto llave en mano de principio a fin en Tepeji del Río, Hidalgo: desde la propuesta de diseño arquitectónico y la ingeniería estructural hasta la ejecución completa del complejo de la planta Tintas Líquidas.",
   "A turnkey project from start to finish in Tepeji del Río, Hidalgo: from the architectural design proposal and structural engineering through full execution of the Tintas Líquidas plant complex.",
   city="Tepeji del Río", article="complejo"),

# ─────────── PUEBLA ───────────
_p("thyssenkrupp","thyssenkrupp","puebla","automotive",2,
   "Oficinas y nave industrial","Offices and industrial facility","18,695 m²",
   ["Oficinas","Nave industrial"]+E, ["Offices","Industrial facility"]+EE,
   "Oficinas y nave industrial de 18,695 m² para thyssenkrupp en el Parque Industrial Xoxtla, Puebla.",
   "18,695 m² of offices and industrial facilities for thyssenkrupp in the Xoxtla Industrial Park, Puebla.",
   city="Parque Industrial Xoxtla"),
_p("audi-puebla","Audi Puebla","puebla","automotive",3,
   "Obra industrial para planta automotriz","Industrial works for an automotive plant",None,
   ["Estructura metálica","Obra industrial"], ["Structural steel","Industrial construction"],
   "Trabajos para la planta de Audi en Puebla, dentro del clúster automotriz del estado.",
   "Works for the Audi plant in Puebla, within the state's automotive cluster."),

# ─────────── TLAXCALA ───────────
_p("vetrotex-saint-gobain","Vetrotex Saint-Gobain","tlaxcala","industrial",3,
   "Nave industrial","Industrial facility",None,
   ["Nave industrial","Estructura metálica","Obra civil"],
   ["Industrial facility","Structural steel","Civil works"],
   "Nave industrial para Vetrotex Saint-Gobain, fabricante de fibra de vidrio, en el Parque Industrial Xicohténcatl, Tlaxcala. La obra se ejecutó dentro de una planta manufacturera en operación.",
   "Industrial facility for Vetrotex Saint-Gobain, a fibreglass manufacturer, in the Xicohténcatl Industrial Park, Tlaxcala. The work was carried out inside an operating manufacturing plant.",
   city="Parque Industrial Xicohténcatl"),

# ─────────── JALISCO ───────────
_p("jugos-del-valle","Jugos del Valle","jalisco","food",3,
   "Nueva nave industrial","New industrial facility","22,000 m²",
   ["Nave de proceso","Almacén"]+E, ["Process building","Warehouse"]+EE,
   "Construcción de la nueva nave industrial de 22,000 m² de Jugos del Valle en Lagos de Moreno, Jalisco, bajo los requisitos del sector alimenticio.",
   "Construction of Jugos del Valle's new 22,000 m² industrial facility in Lagos de Moreno, Jalisco, built to food-industry requirements.",
   city="Lagos de Moreno"),

# ─────────── MICHOACÁN ───────────
_p("ford","Ford","michoacan","automotive",1,
   "Proyecto ejecutivo · agencia","Executive project · dealership","4,280 m²",
   ["Proyecto ejecutivo","Agencia automotriz"], ["Executive project","Automotive dealership"],
   "Proyecto ejecutivo y agencia Ford de 4,280 m² en Morelia, Michoacán.",
   "Executive project and Ford dealership of 4,280 m² in Morelia, Michoacán.",
   city="Morelia"),

# ─────────── AGUASCALIENTES ───────────
_p("tst-timco","TST Inc · TIMCO","aguascalientes","industrial",2,
   "Proyecto ejecutivo","Executive project","15,000 m²",
   ["Proyecto ejecutivo","Nave industrial"], ["Executive project","Industrial facility"],
   "Proyecto ejecutivo de 15,000 m² en el Parque Industrial Los Arellanos, Aguascalientes.",
   "A 15,000 m² executive project in the Los Arellanos Industrial Park, Aguascalientes.",
   city="Parque Industrial Los Arellanos"),

# ─────────── VERACRUZ ───────────
_p("femsa","Coca-Cola FEMSA","veracruz","food",1,
   "Proyecto ejecutivo · nave industrial","Executive project · industrial facility","9,700 m²",
   ["Proyecto ejecutivo","Nave industrial"]+E, ["Executive project","Industrial facility"]+EE,
   "Proyecto ejecutivo y nave industrial de 9,700 m² para Coca-Cola FEMSA en el Parque Industrial Valle de Orizaba, Veracruz.",
   "Executive project and 9,700 m² industrial facility for Coca-Cola FEMSA in the Valle de Orizaba Industrial Park, Veracruz.",
   city="Parque Industrial Valle de Orizaba"),
]

# ───────────────── RESEÑAS REALES (cartas de recomendación) ─────────────────
REVIEWS = [
 dict(client="Gates de México", who="Leonel Magaña C.", role={"es":"Projects","en":"Projects"},
   logo="gates" , sector="automotive",
   text={"es":"Caabsa Steel México realizó satisfactoriamente la ampliación de nave industrial del proyecto High Speed en nuestra planta de Gates Toluca, ejecutando los trabajos de manera perseverante y con soluciones técnicas a los retos presentados durante el apogeo del COVID-19. Caabsa al día de hoy es un proveedor de nuestra compañía.",
         "en":"Caabsa Steel México successfully delivered the industrial facility expansion for the High Speed project at our Gates Toluca plant, carrying out the work with perseverance and with technical solutions to the challenges that arose at the height of COVID-19. Caabsa remains a supplier to our company today."}),
 dict(client="Grupo Sánchez", who="Ing. Jesús Mc. Kelligan Sánchez", role={"es":"Director de Operaciones","en":"Operations Director"},
   logo="grupo-sanchez", sector="corporate",
   text={"es":"Durante la construcción de este complejo, Caabsa Steel México se desempeñó como una empresa seria, capaz, honesta y responsable, cumpliendo en tiempo y forma con los trabajos asignados.",
         "en":"Throughout the construction of this complex, Caabsa Steel México proved to be a serious, capable, honest and responsible company, completing the assigned work on time and as agreed."}),
 dict(client="Martinrea Honsel México", who="Guillermo Huerta González", role={"es":"Purchasing Area","en":"Purchasing Area"},
   logo="martinrea", sector="automotive",
   text={"es":"Caabsa Steel México ha ejecutado, durante ocho años continuos, trabajos de ampliación y mejora de nuestra planta. A lo largo de nuestra relación comercial ha demostrado ser una empresa seria y formal.",
         "en":"Caabsa Steel México has carried out expansion and improvement works at our plant for eight continuous years. Throughout our commercial relationship it has proven to be a serious and reliable company."}),
 dict(client="Coca-Cola FEMSA", who="Ma. de Lourdes Orozco González", role={"es":"Gerente de Abastecimientos Corporativo","en":"Corporate Procurement Manager"},
   logo="femsa", sector="food",
   text={"es":"Caabsa Steel México nos ha demostrado en nuestra relación comercial ser una empresa seria y formal. Durante el desarrollo y ejecución de los trabajos ha cumplido con sus compromisos en tiempo y forma.",
         "en":"In our commercial relationship, Caabsa Steel México has proven to be a serious and reliable company. Throughout the development and execution of the works it has met its commitments on time and as agreed."}),
 dict(client="Dalton Evolución", who="Lic. Rafael Quiroz Galván", role={"es":"Compras Inmobiliaria","en":"Real Estate Procurement"},
   logo="dalton-honda", sector="automotive",
   text={"es":"Caabsa Steel México desarrolló y ejecutó satisfactoriamente los trabajos de construcción de nuestra agencia automotriz Honda Tollocan. A lo largo de nuestra relación comercial ha demostrado ser una empresa seria y formal.",
         "en":"Caabsa Steel México successfully developed and delivered the construction works for our Honda Tollocan dealership. Throughout our commercial relationship it has proven to be a serious and reliable company."}),
 dict(client="Metrocolor de México", who="C.P. Marco Martínez", role={"es":"Administrador","en":"Administrator"},
   logo="", sector="industrial",
   text={"es":"Caabsa Steel México ejecutó satisfactoriamente los trabajos de construcción de nuestra nave industrial en el Parque Industrial Finsa El Marqués, en Querétaro.",
         "en":"Caabsa Steel México successfully delivered the construction works for our industrial facility in the Finsa El Marqués Industrial Park, Querétaro."}),
]
